### ISSUE TITLE
[question] nacos-sdk-rust更新instance list的机制是怎么样的？

### ISSUE THREAD

**Issue by tianyucn** [nacos-group/nacos-sdk-rust#113]
今天遇到一个问题：我们的nacos-server集群挂了，java、node的服务都有错误日志或者告警信息发出，rust的服务没有任何信息。
当前版本:nacos-sdk = { version = "0.2.2" }

有3个问题，希望可以得到帮助：
1. nacos-sdk-rust 是如何更新instance信息的？(我们目前实现了基于nacos-sdk的Instance change事件的监听)

2. 例如今天的情况，nacos-server集群挂了，假设有和nacos-server交互的动作，例如：心跳、周期轮询等，是不是应该报错或者有错误日志？

3. 有没有心跳的机制或者动作？
（对比了java、node的实现，例如node中在注册instance时有这样的动作：`this._beatReactor.addBeatInfo(serviceNameWithGroup, beatInfo);`，抱歉，我在源码中确实没有找到相关的代码，如果有拜托帮忙指引一下）

4. 有没有什么入口或者钩子可以让我们主动感知到nacos-server是否可用或者健康？

**Comment by CherishCai** [comment]
- 建议升级到 0.2.3 
- 回答一个日志问题，我们使用了 tracing 接口，至于具体日志打印，需要自己订阅输出。可以借鉴 https://github.com/opc-source/nacos-sdk-rust-binding-node/blob/main/src/lib.rs#L11-L32

1. 客户端有订阅服务端的数据，如果有变更，就会触发 change 事件，pls see NamingPushRequestHandler, ServiceInfoHolder

3. naming 注册中心的心跳是自动的，注册服务后都会不断心跳保活，pls see naming::redo::mod.rs

4. 第四点需要增加 api 暴露出来健康状态了

**Comment by CherishCai** [comment]
日志丰富和健康状态 api ， @onewe 也看看 💗

**Comment by tianyucn** [comment]
> @tianyucn 另外咨询下，nacos-sdk-rust 对 naming 部分默认是防推空的，所以应该没有产生服务调用问题吧？

没有产生

**Comment by tianyucn** [comment]
> * 建议升级到 0.2.3
> * 回答一个日志问题，我们使用了 tracing 接口，至于具体日志打印，需要自己订阅输出。可以借鉴 https://github.com/opc-source/nacos-sdk-rust-binding-node/blob/main/src/lib.rs#L11-L32
> 
> 1、客户端有订阅服务端的数据，如果有变更，就会触发 change 事件，pls see NamingPushRequestHandler, ServiceInfoHolder
> 
> 3、naming 注册中心的心跳是自动的，注册服务后都会不断心跳保活，pls see naming::redo::mod.rs
> 
> 4、第四点需要增加 api 暴露出来健康状态了

3、谢谢，已经看到了，这里可以理解为每3s进行一次心跳么？如果失败了会有什么动作呢？

**Comment by tianyucn** [comment]
订阅日志发现个问题，我这边已经断网了，依然打印`the current grpc connection state is in ready`

**Comment by CherishCai** [comment]
> 订阅日志发现个问题，我这边已经断网了，依然打印`the current grpc connection state is in ready` 

@tianyucn 如果应用已经启动连接上了服务端，然后断网，nacos-sdk-rust 会不断尝试重连服务端，直至连上。不知道是不是这样产生的？

**Comment by tianyucn** [comment]
有时会打印此类日志，但是时间上不是很确定
![image](https://user-images.githubusercontent.com/51066290/225531487-7fd8f881-b9d6-4233-b483-679f2872a8b6.png)
![image](https://user-images.githubusercontent.com/51066290/225531423-8cfde05a-246a-4899-9805-e93b8a316756.png)

**Comment by CherishCai** [comment]
> 有时会打印此类日志，但是时间上不是很确定： ![image](https://user-images.githubusercontent.com/51066290/225531487-7fd8f881-b9d6-4233-b483-679f2872a8b6.png)
> 
> 如果上面的日志打印，重新联网，会打印下面日志： ![image](https://user-images.githubusercontent.com/51066290/225531423-8cfde05a-246a-4899-9805-e93b8a316756.png)

看起来是没问题的，会不断尝试重连，直至恢复～

**Comment by tianyucn** [comment]
> > 有时会打印此类日志，但是时间上不是很确定： ![image](https://user-images.githubusercontent.com/51066290/225531487-7fd8f881-b9d6-4233-b483-679f2872a8b6.png)
> > 如果上面的日志打印，重新联网，会打印下面日志： ![image](https://user-images.githubusercontent.com/51066290/225531423-8cfde05a-246a-4899-9805-e93b8a316756.png)
> 
> 看起来是没问题的，会不断尝试重连，直至恢复～ 服务端异常时候 nacos-sdk-rust 会继续使用客户端上已有的数据，所以期间会保持稳定

"服务端异常时候 nacos-sdk-rust 会继续使用客户端上已有的数据"，这里如果服务端异常了，是不是应该打印日志，这样能帮助发现问题。如果服务端已经异常了，没有错误日志感觉比较奇怪。

**Comment by CherishCai** [comment]
emmm, 打印的如你图示，订阅日志会有，若希望有更明确更丰富的日志，可以提 PR 在需要的位置输出。🤝

**Comment by CherishCai** [comment]
log change to error, see https://github.com/nacos-group/nacos-sdk-rust/pull/115 `error!("the current grpc connection state is in transient_failure");`

**Comment by CherishCai** [comment]
至于 simple_app 完成启动后，为什么还会一直打印 "receive NotifySubscriberRequest from nacos server" 确实需要查看下 https://github.com/nacos-group/nacos-sdk-rust/issues/116

**Comment by CherishCai** [comment]
> 订阅日志发现个问题，我这边已经断网了，依然打印`the current grpc connection state is in ready` ![image](https://user-images.githubusercontent.com/51066290/225267853-77f5422e-5b69-499e-8cb7-1cfa554f8eb2.png) 另外，网络恢复后，`receive NotifySubscriberRequest from nacos server:`不再打印了

这个问题或许是链接检测不可靠造成的，zk connect 都 ERROR 了，而 nacos-sdk-rust 则还打印出正常状态 cc @onewe

**Comment by onewe** [comment]
server 端不健康或者挂了 这种情况 sdk 内部是有事件的, 后续修复健康检测之后把这个事件开放出来

**Comment by onewe** [comment]
考虑到用户使用内部事件的方式来检测 状态是否正常 这种使用方式的成本比较高, 看看小伙伴是否有其他方案, 或者是否真有这种使用场景?

**Comment by tianyucn** [comment]
> 考虑到用户使用内部事件的方式来检测 状态是否正常 这种使用方式的成本比较高, 看看小伙伴是否有其他方案, 或者是否真有这种使用场景?

其实把日志打印清楚，从业务层面就可以做到一些基础的告警了，例如：在关键的地方打印一些error日志

**Comment by onewe** [comment]
@tianyucn 这个目前测试了一下 没得问题 , 你看有时间了 测试一波？

**Comment by CherishCai** [comment]
> 其实把日志打印清楚，从业务层面就可以做到一些基础的告警了，例如：在关键的地方打印一些error日志

日志已经改了的  see https://github.com/nacos-group/nacos-sdk-rust/pull/115 `error!("the current grpc connection state is in transient_failure");`

**Comment by tianyucn** [comment]
> @tianyucn 这个目前测试了一下 没得问题 , 你看有时间了 测试一波？

没问题，等新版本了
