### ISSUE TITLE
BUG: Connection closed by server and then `Connection is unregistered`

### ISSUE THREAD

**Issue by tianyucn** [nacos-group/nacos-sdk-rust#134]
今天发现集群中部分节点在获取instances时报错，重启后恢复，过一段时间又会出现节点报错，不是全部节点都报错。

调用的这个方法：
fn get_all_instances(
        &self,
        service_name: String,
        group_name: Option<String>,
        clusters: Vec<String>,
        subscribe: bool,
    ) -> Result<Vec<ServiceInstance>>;

2023-04-01 21:45:03.478 ERROR Deserialize from Any to GrpcMessage occur an error:Serialization(Error("missing field `serviceInfo`", line: 1, column: 90))
2023-04-01 21:45:03.479 ERROR unary_call_async response grpc message convert to message object occur an error. Serialization(Error("missing field `serviceInfo`", line: 1, column: 90))

**Comment by CherishCai** [comment]
是不是启动时？或者重链后短暂的分钟内异常？
我当时也在测试验证出现过，重连过程不是很稳定会有些短暂异常，不过最多分钟级就消失

**Comment by CherishCai** [comment]
> 是不是启动时？或者重链后短暂的分钟内异常？ 我当时也在测试验证出现过，重连过程不是很稳定会有些短暂异常，不过最多分钟级再次重连达到稳定然后异常消失

@tianyucn 在出现异常之前的日志中，看看是否有链接相关的日志打印

**Comment by tianyucn** [comment]
> 是不是启动时？或者重链后短暂的分钟内异常？ 我当时也在测试验证出现过，重连过程不是很稳定会有些短暂异常，不过最多分钟级再次重连达到稳定然后异常消失

不是启动时，正常运行出现的。一直有，分钟级别没有恢复

**Comment by tianyucn** [comment]
> > 是不是启动时？或者重链后短暂的分钟内异常？ 我当时也在测试验证出现过，重连过程不是很稳定会有些短暂异常，不过最多分钟级再次重连达到稳定然后异常消失
> 
> 不是启动时，正常运行出现的。一直有，分钟级别没有恢复

info error级别日志中没有打印这个信息

**Comment by CherishCai** [comment]
参数 `subscribe: false` 对吧？实时发起远程请求到了服务端，咋感觉向是服务端返回的数据不包含 `serviceInfo`

以下这段代码仅是对返回的数据的 json 反序列化，出现你描述的那个异常
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/16837364/229294101-f903a5be-8af1-4fb1-94fb-e99525bdd899.png">

**Comment by CherishCai** [comment]
如果不是需要实时请求数据，建议 `subscribe: true` 准实时订阅拿到最新数据。
而针对这个异常需要知道到底是否服务端返回的数据有问题了而不是完整的格式，代码看不出什么毛病

**Comment by tianyucn** [comment]
> 参数 `subscribe: false` 对吧？实时发起远程请求到了服务端，咋感觉是服务端返回的数据不包含 `serviceInfo`
> 
> 以下这段代码仅是对返回的数据的 json 反序列化，出现你描述的那个异常 <img alt="image" width="1087" src="https://user-images.githubusercontent.com/16837364/229294101-f903a5be-8af1-4fb1-94fb-e99525bdd899.png">

是的，subscribe: false

**Comment by CherishCai** [comment]
🤔 或者在数据格式异常时候，打印完整的内容体，辅助排查 cc @onewe

**Comment by tianyucn** [comment]
> 如果不是需要实时请求数据，建议 `subscribe: true` 准实时订阅拿到最新数据。 而针对这个异常需要知道到底是否服务端返回的数据有问题了而不是完整的格式，代码看不出什么毛病

好的，下周我找server端同学看一下。另外，如果改成subscribe=true，会有改善吗？

**Comment by CherishCai** [comment]
`subscribe=true` 的话，客户端会启用订阅模式，会不断准实时订阅服务端的数据更新到客户端的缓存里；
基于这样的话，客户端就不是每次实时请求服务端，大规模调用的话性能高也不会对服务端造成多大压力。

准实时（几十毫秒内就会获得最新数据）绝大多数场景下够用的，一般的 RPC 也都是订阅注册中心发现最新服务即可。
当然得看你的实际场景了。

**Comment by onewe** [comment]
感谢反馈, 下周紧锣密鼓的改

**Comment by tianyucn** [comment]
> 🤔 或者在数据格式异常时候，打印完整的内容体 String，辅助排查 cc @onewe

这个事情如果有结论，或者发现问题，麻烦这里给个反馈，感谢

**Comment by CherishCai** [comment]
我们虽然维护，但工作中还没有 Rust 应用，所以发现问题的机会很少 😭，我建议 `subscribe=true` 就好。
至于异常内容体那个后面加上日志，等再次遇到了就容易排查

**Comment by tianyucn** [comment]
> 我们虽然维护，但工作中还没有 Rust 应用，所以发现问题的机会很少 😭，我建议 `subscribe=true` 就好。 至于异常内容体那个后面加上日志，等再次遇到了就容易排查

好的，subscribe=true 这个配置我这边会同步测试的

**Comment by tianyucn** [comment]
> `subscribe=true` 的话，客户端会启用订阅模式，会不断准实时订阅服务端的数据更新到客户端的缓存里； 基于这样的话，客户端就不是每次实时请求服务端，大规模调用的话性能高也不会对服务端造成多大压力。
> 
> 准实时（秒级内就会获得最新数据）绝大多数场景下够用的，一般的 RPC 也都是订阅注册中心发现最新服务即可。 当然得看你的实际场景了。

这里客户端多久更新一次数据到本地缓存？

**Comment by onewe** [comment]
默认配置来看是 1分钟一次

**Comment by CherishCai** [comment]
> 默认配置来看是 1分钟一次

大佬你实现的订阅 List-Watch 💗，服务端准实时通知，客户端兜底 10s 轮询呐。所以 naming 订阅是准实时更新本地缓存吧？秒级别内就刷新了

**Comment by tianyucn** [comment]
去掉了对get_all_instances方法的依赖，直接调用api解决了这个问题。

错误依然存在是ncos-sdk，定时任务报错的，默认1分钟。

**Comment by onewe** [comment]
@tianyucn 你能提供一下复现的步骤嘛, 我这边正在处理 方便验证

**Comment by CherishCai** [comment]
> 去掉了对get_all_instances方法的依赖，直接调用api解决了这个问题。

请问改为直接调用哪个 api ?

**Comment by CherishCai** [comment]
> @tianyucn 你能提供一下复现的步骤嘛, 我这边正在处理 方便验证

@onewe 感觉先加一个打印异常内容体 str 日志，就容易排查

**Comment by tianyucn** [comment]
> @tianyucn 你能提供一下复现的步骤嘛, 我这边正在处理 方便验证

复现步骤未知，但是是必现的问题，且无法自动恢复，我们80个节点，目前随机有1个节点有问题。

**Comment by tianyucn** [comment]
> > 去掉了对get_all_instances方法的依赖，直接调用api解决了这个问题。
> 
> 请问改为直接调用哪个 api ?

nacos/v1/ns/instance/list，但是这个问题和这个步骤无关

**Comment by tianyucn** [comment]
> 如果随机某节点持久异常，咋感觉还是连接层面的出了问题 😂

异常节点，在nacos后台查不到，已经没有注册信息了

**Comment by darcydai** [comment]
@onewe @tianyucn 
我来补充一下关于这个问题更多的context。
通过对出现问题的pod 进行tcpdump抓包 通过wireshark 分析proto 得到nacos server 返回的是body 是
`{"resultCode":500,"errorCode":301,"message":"Connection is unregistered.","success":false}`
通过阅读nacos server 的代码得知是因  ConnectionManager 不存在这个连接
![image](https://user-images.githubusercontent.com/20854418/230532321-727d8ec2-8cd9-43e3-9aad-295d316353f0.png)

1. 排查发现 grpc连接存在重新创建的问题，pod 启动的时间是上午十一点左右，通过查阅nacos server remote-digist.log 得知这个连接在 出现问题的时候出现了断开。
![image](https://user-images.githubusercontent.com/20854418/230531355-c616e38e-cf2c-4f7b-b8c3-aafa8681c4bb.png)
![image](https://user-images.githubusercontent.com/20854418/230531371-71d41851-e991-465b-8ccd-ee78341cb3a2.png)
2. 根据日志定位到nacos server的代码发现是因为 nacos server 关于outdata 的连接存在活跃周期检查(这个活跃周期) 如果大于20s没有活跃则会向客户端发送一个 client dection 的请求 判断当前客户端是否存活
![image](https://user-images.githubusercontent.com/20854418/230531641-19930e8d-fa2d-4f28-8e3a-121ac4b8f4b2.png)
![image](https://user-images.githubusercontent.com/20854418/230531713-e9a6e41e-330f-4376-a1b3-16ae50126e9a.png) 
如果超过三秒客户端的没有响应(server 请求客户端) 则server 会将该连接真正的移除 然后关闭。

此后客户端创建了新的连接，一致在报连接未注册的问题。

**Comment by onewe** [comment]
看样子是 重连之后没有重新注册

**Comment by onewe** [comment]
感谢反馈

**Comment by CherishCai** [comment]
>    ![image](https://user-images.githubusercontent.com/20854418/230531371-71d41851-e991-465b-8ccd-ee78341cb3a2.png)

但是看这个日志，server 刚发起检测，就立马断了 😭 防不胜防，还是客户端主动 health-check 重连。。。

**Comment by darcydai** [comment]
两个问题
1. 通过查询nacos server代码发现 connection register 来自于 客户端发送的  ConnectionSetupRequest
![image](https://user-images.githubusercontent.com/20854418/230534286-8312ec6b-b87f-4ea8-a40c-432774c1af4c.png)
 不确定客户端重连以后有没有发送
2. active time 的刷新机制 主要是几种途径 server 发送探测任务 并收到客户端的返回 会刷新、客户端有请求过来 如果是request 也会刷新，所以另一方面要减少  active time 的事件 尽量少发生。

**Comment by darcydai** [comment]
> > ![image](https://user-images.githubusercontent.com/20854418/230531371-71d41851-e991-465b-8ccd-ee78341cb3a2.png)
> 
> 看这个日志，server 刚发起检测，就立马断了 😭 防不胜防，还是得客户端主动 health-check 重连。。。

这个日志是旧的连接关闭的（早上十一点十分创建），新的连接看日志像是从来就没有注册过，所以需要确认 重新连接以后 客户端有没有重发 ConnectionSetupRequest

**Comment by darcydai** [comment]
我晚点测试一下java 客户端这种 active time  超过阈值的问题 发生的频繁吗 后续我会持续跟进这个问题。

**Comment by darcydai** [comment]
我找了 一个只有java 服务注册的nacos server 版本是2.0.3  看日志应该是没有出现过 服务端因为active time 超出阈值向客户端探测的日志 和  连接超时的日志
![image](https://user-images.githubusercontent.com/20854418/230541235-0c6c3cee-b45a-46d3-a61c-220278efef72.png)

**Comment by CherishCai** [comment]
是的 Java 客户端不会有这个问题，它会间隔 5s 发起 health-check 。我们实现 Rust 的时候偷懒了没做这件事，暂时依赖服务端的检测，没想到这样偶然性掉坑～

**Comment by darcydai** [comment]
嗯嗯 找到JAVA client 相关的逻辑了，辛苦有空给修复一下。我不太懂rust 不然就自己修😄 提pr了

**Comment by darcydai** [comment]
> 是的 Java 客户端不会有这个问题，它会间隔 5s 发起 health-check 。我们实现 Rust 的时候偷懒了没做这件事，暂时依赖服务端的检测，没想到这样偶然性掉坑～

ConnectionSetupRequest 这个也需要确认一下 server 断开后重连 客户端有没有发送这个

**Comment by CherishCai** [comment]
> ConnectionSetupRequest 这个也需要确认一下 server 断开后重连 客户端有没有发送这个

本地测试进行重连都会发的，可能这是一个服务端主动 close 的逻辑，超出了逻辑之外，没有被验证过。近期会修一版加上客户端的 health-check ～

**Comment by CherishCai** [comment]
有些奇怪，我本地尝试不回复 ClientDetectionResponse 是会触发重链的；
所以比较奇怪为啥你那边服务端 close 后客户端没有重连？
![image](https://user-images.githubusercontent.com/16837364/231632334-a9d97cfc-da03-436c-862d-9ea5aec126d4.png)

**Comment by CherishCai** [comment]
再补充一下：根据我跑 simple_app 去掉 ClientDetectionRequestHandler 的回复，感觉 config 部分是重连成功的，而 naming 的还是失败
![image](https://user-images.githubusercontent.com/16837364/231670891-c5c747d6-8dde-46c6-bd83-1324d68e5c00.png)

**Comment by CherishCai** [comment]
再补充下：只丢弃前 `ClientDetectionRequestHandler` 两个回复，都是重连成功的
![image](https://user-images.githubusercontent.com/16837364/231675651-453d07a0-f0f7-4890-9760-8c9d31ca70be.png)

**Comment by onewe** [comment]
@tianyucn @shenshouer 搞定. 如果你们有时间的话可以测试一波.

**Comment by CherishCai** [comment]
请尝试下 0.2.5 版本，加了客户端主动健康检测

**Comment by CherishCai** [comment]
close with https://github.com/nacos-group/nacos-sdk-rust/pull/139

**Comment by tianyucn** [comment]
> @tianyucn @shenshouer 搞定. 如果你们有时间的话可以测试一波.

本地测试没有问题
