### ISSUE TITLE
BUG: msvc下的tokio::test宏代码发生死锁

### ISSUE THREAD

**Issue by gy0801151351** [nacos-group/nacos-sdk-rust#143]
操作系统: Windows 11 专业版  22000.1817
nacos-sdk 版本: 0.2.5
rustc版本: 1.68.1
rustc工具链:  stable-x86_64-pc-windows-msvc
tokio版本: 1.27.0

`
#[allow(unused)]
#[cfg(test)]
mod test {
    use nacos_sdk::api::{config::{ConfigServiceBuilder, ConfigService}, props::ClientProps};

    #[ignore]
    #[tokio::test]
    async fn test() -> Result<(), Box<dyn std::error::Error>> {
        let config_service = ConfigServiceBuilder::new(
            ClientProps::new()
                .server_addr("127.0.0.1:8848")
                .namespace("")
                .app_name("tina-core")
                .auth_username("test")
                .auth_password("123456"),
        )
        .enable_auth_plugin_http()
        .build()?;
        let res = config_service.get_config("test".to_string(), "DEFAULT_GROUP".to_string()).await?;
        let content = res.content();
        println!("{content}");
        Ok(())
    }
}
`

**Comment by CherishCai** [comment]
据说 `#[tokio::test]` 是单线程的，所以这个包内有多线程等待，就会卡死了。

**Comment by gy0801151351** [comment]
我想原因也是这个, 不过建议考虑一下是否要支持单线程的tokio, 因为像 actix-web, ntex这些的业务tokio模型是工作在单线程模式下的

**Comment by CherishCai** [comment]
应该是 auth_plugin_http 那个实现带入的，之前我在它下面写的测试用例就死锁 😂 ，我还没处理。
若有空的话你可以提个修正 PR 吗？

**Comment by gy0801151351** [comment]
[https://github.com/nacos-group/nacos-sdk-rust/pull/145#issue-1674161639](url)

**Comment by CherishCai** [comment]
close with https://github.com/nacos-group/nacos-sdk-rust/pull/145
