### ISSUE TITLE
Bug: 开启 auth 造成卡住，日志不再输出，可能服务也会下线！

### ISSUE THREAD

**Issue by CherishCai** [nacos-group/nacos-sdk-rust#161]
### 解决方案
- 将会在 0.3.x 做 Break Change，调整插件 api 为 async

### 复现手段
默认 auth 为 (`let delay_sec = login_response.token_ttl / 10;`)  30min 复现卡住；
可以调整为 `let delay_sec = login_response.token_ttl / 100;` 3min 复现

### 现象如下
1. 【新逻辑】卡在 receiver.recv()
![image](https://github.com/nacos-group/nacos-sdk-rust/assets/16837364/a55c22fb-2db0-4994-8044-42c175985d9c)

2. 【旧逻辑】卡在 futures::executor::block_on(future)
![image](https://github.com/nacos-group/nacos-sdk-rust/assets/16837364/1b213e81-6057-458e-9eb5-f31b58db06c4)

**Comment by CherishCai** [comment]
@gy0801151351 请关注

**Comment by CherishCai** [comment]
本地运行时候服务都在，配置监听也在。而容器运行可能服务会下线！

**Comment by gy0801151351** [comment]
查看了代码, 发现是合并了一段中间代码. 这个地方我改了两次, 第一次是使用channel, 第二次是使用executor.

**Comment by CherishCai** [comment]
It seems like https://github.com/tokio-rs/tokio/issues/4730
