### ISSUE TITLE
Test: Integration Test with nacos-server

### ISSUE THREAD

**Issue by CherishCai** [nacos-group/nacos-sdk-rust#171]
RT, 可借鉴 https://github.com/etcdv3/etcd-client/blob/master/.github/workflows/ci.yml

**Comment by mxsm** [comment]
@CherishCai  I  want try

**Comment by mxsm** [comment]
@CherishCai  I want to try, Please assign it to me.

**Comment by CherishCai** [comment]
@mxsm Welcome 🎉🎉
