### ISSUE TITLE
本机测试，在控制台服务列表中未看到服务，跪求问题所在

### ISSUE THREAD

**Issue by jinkaz** [nacos-group/nacos-sdk-rust#178]
环境：window10,
nacos：2.0.3 单机运行
web框架：rocket
```rust
use std::sync::Arc;
use nacos_sdk::api::constants;
use nacos_sdk::api::naming::{NamingChangeEvent, NamingEventListener, NamingServiceBuilder, ServiceInstance,NamingService};
use nacos_sdk::api::props::ClientProps;
use rocket::{Build, fairing, Rocket};

pub struct ServiceManager;

struct ServiceInstanceChangeListener;

impl NamingEventListener for ServiceInstanceChangeListener{
    fn event(&self, event: Arc<NamingChangeEvent>) {
        tracing::info!("subscriber notify event={:?}", event);
    }
}


impl ServiceManager {
    pub async fn register(_rocket: Rocket<Build>)->fairing::Result{
        let client_props = ClientProps::new()
            .server_addr("192.168.135.1:8848")
            // .remote_grpc_port(9838)
            // Attention! "public" is "", it is recommended to customize the namespace with clear meaning.
            .namespace("public")
            .app_name("rust_app")
            .auth_username("nacos") // TODO You can choose not to enable auth
            .auth_password("nacos") // TODO You can choose not to enable auth
            ;

        let naming_service = NamingServiceBuilder::new(client_props).build().expect("nacos 注册失败");
       // naming subscriber
        let subscriber = Arc::new(ServiceInstanceChangeListener);
        let _subscribe_ret = naming_service.subscribe(
            "rust-sample-service".to_string(),
            Some(constants::DEFAULT_GROUP.to_string()),
            Vec::default(),
            subscriber,
        );

        // register instances
        let sample_rust = ServiceInstance {
            ip: "192.168.135.1".to_string(),
            port: 8000,
            ..Default::default()
        };
        let _register_instance_ret = naming_service.batch_register_instance(
            "rust-sample-service".to_string(),
            Some(constants::DEFAULT_GROUP.to_string()),
            vec![sample_rust],
        );

        Ok(_rocket)
    }
}
```

**Comment by jinkaz** [comment]
这是启动后的日志：

    Finished dev [unoptimized + debuginfo] target(s) in 0.48s
     Running `target\debug\main.exe`
SET sql_mode=(SELECT CONCAT(@@sql_mode, ',PIPES_AS_CONCAT,NO_ENGINE_SUBSTITUTION')),time_zone='+00:00',NAMES …; rows affected: 0, rows returned: 0, elapsed: 1.248ms

SET
  sql_mode =(
    SELECT
      CONCAT(
        @ @sql_mode,
        ',PIPES_AS_CONCAT,NO_ENGINE_SUBSTITUTION'
      )
  ),
  time_zone = '+00:00',
  NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

Warning: cannot deserialize C:\Users\jim\nacos\naming\public\DEFAULT_GROUP%40%40credit-service@@DEFAULT, missing field `groupName` at line 1 column 195.
Warning: cannot deserialize C:\Users\jim\nacos\naming\public\DEFAULT_GROUP%40%40healthCode-service@@DEFAULT, missing field `groupName` at line 1 column 589.
Warning: cannot deserialize C:\Users\jim\nacos\naming\public\DEFAULT_GROUP%40%40limitdisplay-service, missing field `groupName` at line 1 column 571.
Warning: cannot deserialize C:\Users\jim\nacos\naming\public\DEFAULT_GROUP%40%40limitdisplay-service@@DEFAULT, missing field `groupName` at line 1 column 201.
Warning: cannot deserialize C:\Users\jim\nacos\naming\public\DEFAULT_GROUP%40%40loansdisplay-service@@DEFAULT, missing field `groupName` at line 1 column 595.
Warning: cannot deserialize C:\Users\jim\nacos\naming\public\DEFAULT_GROUP%40%40loanssyn-service@@DEFAULT, missing field `groupName` at line 1 column 583.
Warning: cannot deserialize C:\Users\jim\nacos\naming\public\DEFAULT_GROUP%40%40manor-core@@DEFAULT, missing field `groupName` at line 1 column 191.
Warning: cannot deserialize C:\Users\jim\nacos\naming\public\DEFAULT_GROUP%40%40sample-service, missing field `groupName` at line 1 column 547.
Warning: cannot deserialize C:\Users\jim\nacos\naming\public\DEFAULT_GROUP%40%40sms-service@@DEFAULT, missing field `groupName` at line 1 column 568.
service info observe task start!
create new connection.
the new connection is initializing.
setup connection
the new connection is initializing.
connection health check
the new connection is initializing.
check server
the new connection is initializing.
CREATE TABLE IF NOT …; rows affected: 0, rows returned: 0, elapsed: 2.901ms

CREATE TABLE IF NOT EXISTS `seaql_migrations` (
  `version` varchar(255) NOT NULL PRIMARY KEY,
  `applied_at` bigint NOT NULL
)

the new connection init completed. connection id :1688033855245_192.168.135.1_6532
Applying all pending migrations
connection 1688033855245_192.168.135.1_6532 connected.
on_grpc_client_reconnect; client_id="naming:192.168.135.1:8848:public:1"
SET sql_mode=(SELECT CONCAT(@@sql_mode, ',PIPES_AS_CONCAT,NO_ENGINE_SUBSTITUTION')),time_zone='+00:00',NAMES …; rows affected: 0, rows returned: 0, elapsed: 645.900µs

SET
  sql_mode =(
    SELECT
      CONCAT(
        @ @sql_mode,
        ',PIPES_AS_CONCAT,NO_ENGINE_SUBSTITUTION'
      )
  ),
  time_zone = '+00:00',
  NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT …; rows affected: 0, rows returned: 0, elapsed: 2.624ms

CREATE TABLE IF NOT EXISTS `seaql_migrations` (
  `version` varchar(255) NOT NULL PRIMARY KEY,
  `applied_at` bigint NOT NULL
)

CREATE TABLE IF NOT …; rows affected: 0, rows returned: 0, elapsed: 2.331ms

CREATE TABLE IF NOT EXISTS `seaql_migrations` (
  `version` varchar(255) NOT NULL PRIMARY KEY,
  `applied_at` bigint NOT NULL
)

CREATE TABLE IF NOT …; rows affected: 0, rows returned: 0, elapsed: 2.393ms

CREATE TABLE IF NOT EXISTS `seaql_migrations` (
  `version` varchar(255) NOT NULL PRIMARY KEY,
  `applied_at` bigint NOT NULL
)

SELECT `seaql_migrations`.`version`, `seaql_migrations`.`applied_at` FROM …; rows affected: 0, rows returned: 1, elapsed: 508.400µs

SELECT
  `seaql_migrations`.`version`,
  `seaql_migrations`.`applied_at`
FROM
  `seaql_migrations`
ORDER BY
  `seaql_migrations`.`version` ASC

Configured for debug.
   >> address: 127.0.0.1
   >> port: 8000
   >> workers: 16
   >> max blocking threads: 512
   >> ident: Rocket
   >> IP header: X-Real-IP
   >> limits: bytes = 8KiB, data-form = 2MiB, file = 1MiB, form = 32KiB, json = 1MiB, msgpack = 1MiB, string = 8KiB
   >> temp dir: C:\Users\jim\AppData\Local\Temp\
   >> http/2: true
   >> keep-alive: 5s
   >> tls: disabled
   >> shutdown: ctrlc = true, force = true, grace = 2s, mercy = 3s
   >> log level: normal
   >> cli colors: true
Routes:
   >> (monitor) GET /sample/monitor
   >> (save_user) POST /sample/user/save
   >> (get_user) GET /sample/user/<id>
   >> (page_user) POST /sample/user/page
   >> (save_redis) POST /sample/redis/save
   >> (get_redis) GET /sample/redis/<id>
   >> (update_user) POST /sample/user/update
   >> (delete_user) GET /sample/user/remove/<id>
Catchers:
   >> (default_catcher) default
Fairings:
   >> ServiceCenter (ignite)
   >> Shield (liftoff, response, singleton)
   >> Migrations (ignite)
   >> 'test' Database Pool (ignite)
Shield:
   >> Permissions-Policy: interest-cohort=()
   >> X-Content-Type-Options: nosniff
   >> X-Frame-Options: SAMEORIGIN
Rocket has launched from http://127.0.0.1:8000
Warning: stop health check task.

**Comment by CherishCai** [comment]
不知道 namespace=public 是否有坑，建议换一个命名空间试试。

**Comment by CherishCai** [comment]
我们之前本地测试用的 nacos-server 2.1.0，以及最新的 2.2.2 都可以

**Comment by CherishCai** [comment]
naming_service 要一直持有，不能让给 drop l了

**Comment by jinkaz** [comment]
> naming_service 要一直持有，不能让给 drop l了

换成nacos2.2.3跑了example是能看到了，啧啧。我得看怎么拆解到我得服务里，谢谢大神
