### ISSUE TITLE
sample_app 运行疑问

### ISSUE THREAD

**Issue by jinkaz** [nacos-group/nacos-sdk-rust#179]
再请教下各位大神：
```rust
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    tracing_subscriber::fmt()
        // all spans/events with a level higher than TRACE (e.g, info, warn, etc.)
        // will be written to stdout.
        .with_max_level(tracing::Level::DEBUG)
        // sets this to be the default, global collector for this application.
        .init();

    let client_props = ClientProps::new()
        .server_addr("192.168.135.1:8848")
        // .remote_grpc_port(9838)
        // Attention! "public" is "", it is recommended to customize the namespace with clear meaning.
        .namespace("f0310bf8-9fb1-466e-8f79-35f91340a6e1")
        .app_name("simple_app")
        .auth_username("nacos") // TODO You can choose not to enable auth
        .auth_password("nacos") // TODO You can choose not to enable auth
        ;

    // ----------  Config  -------------
    // let config_service = ConfigServiceBuilder::new(client_props.clone())
    //     .enable_auth_plugin_http() // TODO You can choose not to enable auth
    //     .build()?;
    // let config_resp = config_service.get_config("todo-data-id".to_string(), "LOVE".to_string());
    // match config_resp {
    //     Ok(config_resp) => tracing::info!("get the config {}", config_resp),
    //     Err(err) => tracing::error!("get the config {:?}", err),
    // }
    //
    // let _listen = config_service.add_listener(
    //     "todo-data-id".to_string(),
    //     "LOVE".to_string(),
    //     std::sync::Arc::new(SimpleConfigChangeListener {}),
    // );
    // match _listen {
    //     Ok(_) => tracing::info!("listening the config success"),
    //     Err(err) => tracing::error!("listen config error {:?}", err),
    // }

    // ----------  Naming  -------------
    let naming_service = NamingServiceBuilder::new(client_props)
        // .enable_auth_plugin_http() // TODO You can choose not to enable auth
        .build()?;

    let listener = std::sync::Arc::new(SimpleInstanceChangeListener);
    let _subscribe_ret = naming_service.subscribe(
        "test-service".to_string(),
        Some(constants::DEFAULT_GROUP.to_string()),
        Vec::default(),
        listener,
    );

    let service_instance1 = ServiceInstance {
        ip: "127.0.0.1".to_string(),
        port: 9090,
        ..Default::default()
    };
    let _register_instance_ret = naming_service.batch_register_instance(
        "test-service".to_string(),
        Some(constants::DEFAULT_GROUP.to_string()),
        vec![service_instance1],
    );
    // tokio::time::sleep(tokio::time::Duration::from_millis(666)).await;

    let instances_ret = naming_service.get_all_instances(
        "test-service".to_string(),
        Some(constants::DEFAULT_GROUP.to_string()),
        Vec::default(),
        false,
    );
    // match instances_ret {
    //     Ok(instances) => tracing::info!("get_all_instances {:?}", instances),
    //     Err(err) => tracing::error!("naming get_all_instances error {:?}", err),
    // }

    tokio::time::sleep(tokio::time::Duration::from_secs(300)).await;

    Ok(())
}
```

最后一个tokio::time::sleep(tokio::time::Duration::from_secs(300)).await; 语句，
如果去掉了，控制台服务列表看不到注册成功。只有开启才可以。我理解这句话是异步转
同步的场景吧，但为什么会导致服务注册成功标志呢

**Comment by CherishCai** [comment]
sleep 是为了让进程在线，要不进程结束了就看不到其在 nacos-server 上的信息。

**Comment by CherishCai** [comment]
进程下线了，nacos-server 健康检测就会去掉你的客户端

**Comment by CherishCai** [comment]
为了模拟应用进程长期在线罢了，就是做了例子。所以应用真实使用的时候，应该初始化 nacos 客户端后一直持有，等应用下线时可以主动注销等等

**Comment by jinkaz** [comment]
> 为了模拟应用进程长期在线罢了，就是做了例子。所以应用真实使用的时候，应该初始化 nacos 客户端后一直持有，等应用下线时可以主动注销等等

好的，谢谢解答

**Comment by jinkaz** [comment]
> 为了模拟应用进程长期在线罢了，就是做了例子。所以应用真实使用的时候，应该初始化 nacos 客户端后一直持有，等应用下线时可以主动注销等等

大神。我这边在rocket中集成nacos-sdk。按您的指点，需要持有nacos客户端。我使用rocket的state或者是fairing试了下都无法
成功。全局能持有应该就只有state了，但是控制台上启动没看到成功。可否劳烦大神指导是哪里除了问题。
main函数：
#[rocket::main]
async fn main()-> Result<(), Box<dyn std::error::Error>>{
    let _rocket= rocket::build().attach(Db::init())
        .attach(AdHoc::try_on_ignite("Migrations", run_migrations))
        .mount("/sample", routes![monitor])
        .mount("/sample", routes![save_user,get_user,update_user,page_user,delete_user])
        .mount("/sample", routes![save_redis,get_redis])
        .register("/", catchers![default_catcher])
        .manage(RedisManager::init("redis://:123456@192.168.135.138:6379/"))
        .manage(Sm::init())
        .launch()
        .await?;

    Ok(())
}

nacos的相关代码也即Sm:init函数：
pub struct Sm;

impl Sm {
    pub  fn init()->impl NamingService{
        let client_props = ClientProps::new()
            .server_addr("192.168.135.1:8848")
            // .remote_grpc_port(9838)
            // Attention! "public" is "", it is recommended to customize the namespace with clear meaning.
            .namespace("f0310bf8-9fb1-466e-8f79-35f91340a6e1")
            .app_name("simple_app")
            .auth_username("nacos") // TODO You can choose not to enable auth
            .auth_password("nacos") // TODO You can choose not to enable auth
            ;

// ----------  Naming  -------------
        let naming_service = NamingServiceBuilder::new(client_props)
            // .enable_auth_plugin_http() // TODO You can choose not to enable auth
            .build().expect("err nameing");

        let listener = std::sync::Arc::new(SimpleInstanceChangeListener);
        naming_service.subscribe(
            "test-service".to_string(),
            Some(constants::DEFAULT_GROUP.to_string()),
            Vec::default(),
            listener,
        );


        let service_instance1 = ServiceInstance {
            ip: "127.0.0.1".to_string(),
            port: 8000,
            ..Default::default()
        };
         naming_service.batch_register_instance(
            "test-service".to_string(),
            Some(constants::DEFAULT_GROUP.to_string()),
            vec![service_instance1],
        );

        naming_service
    }
}
struct SimpleConfigChangeListener;

impl ConfigChangeListener for SimpleConfigChangeListener {
    fn notify(&self, config_resp: ConfigResponse) {
        tracing::info!("listen the config={}", config_resp);
    }
}

pub struct SimpleInstanceChangeListener;

impl NamingEventListener for SimpleInstanceChangeListener {
    fn event(&self, event: std::sync::Arc<NamingChangeEvent>) {
        tracing::info!("subscriber notify: {:?}", event);
    }
}

另外：我发现启动时日志中也有个报错：
Error: connection health check failed convert to grpc message failed. request_id:None ret_code:500 error_code:301 message:Some("Connection is unregistered.")
不知道是不是也有这个的原因。

**Comment by jinkaz** [comment]
> 作为个 struct 属性 `Arc<NamingService>` ？你的经验应该比我丰富呀。我没实际开发过 rust 应用

这也试过了，不行。感觉不像是这个问题

**Comment by jinkaz** [comment]
我问问rocket官方看看我的写法有没有问题，确定下是不是真是没有全局持有nameservice的缘故

**Comment by CherishCai** [comment]
nameservice 与 rocket 应该没啥关系的，各自有逻辑。可以看下 dubbo-rust 或者哪里用过 nacos-sdk-rust 或者对照下 etcd-rs zookeeper 都是一样的，作为一个 lib sdk

**Comment by jinkaz** [comment]
> 

> nameservice 与 rocket 应该没啥关系的，各自有逻辑。可以看下 dubbo-rust 或者哪里用过 nacos-sdk-rust 或者对照下 etcd-rs zookeeper 都是一样的，作为一个 lib sdk

这个问题有新进展。我发现是naming_service 的subscribe等方法根本没执行到，不知道是不是属性宏instrument执行有问题。另外我尝试把源码中的example代码全部拷贝到一个新的cargo工程里，也是没法在控制台上显示。只有在源码工程里运行才会在控制台上显示。是不是有什么特殊的依赖决定了服务注册的问题

**Comment by onewe** [comment]
检查一下有没有相关的日志输出, 还有一点就是 `NamingService` 不能被 `Drop` 掉

**Comment by onewe** [comment]
你可以提交一个 demo 方便排查问题

**Comment by onewe** [comment]
`Error: connection health check failed convert to grpc message failed. request_id:None ret_code:500 error_code:301 message:Some("Connection is unregistered.")` 这个日志是正常的, 发生在连接上了 `nacos server` 但还没注册连接

**Comment by jinkaz** [comment]
> `Error: connection health check failed convert to grpc message failed. request_id:None ret_code:500 error_code:301 message:Some("Connection is unregistered.")` 这个日志是正常的, 发生在连接上了 `nacos server` 但还没注册连接

搞定了！！！！！！subscribe和batch_regist 是异步的，要await！！！！

**Comment by jinkaz** [comment]
我想哭

**Comment by onewe** [comment]
可以笑一笑

**Comment by jinkaz** [comment]
也感谢两位社区的大神还能给我回复
