### ISSUE TITLE
0.3.3 get_config 报Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by zhiweishq** [nacos-group/nacos-sdk-rust#208]
你好，这边使用了[rnacos ](https://github.com/heqingpan/rnacos)
然后配置了 
![image](https://github.com/nacos-group/nacos-sdk-rust/assets/13491101/3657744c-aac8-4803-8b9e-6b68ea6ab7e7)
获取配置
`
let config_service = ConfigServiceBuilder::new(
        ClientProps::new()
        .server_addr("127.0.0.1:8848").namespace("").app_name("test_nacos")
    ).build()?;
    let config_resp = config_service.get_config("login".to_string(), "test".to_string());
    match config_resp {
        Ok(config_resp) =>tracing::info!("get the config success {}", config_resp),
        Err(err) =>tracing::error!("get the config error {:?}", err),
    }
    Ok(())
`
启动后都报这个问题，然后获取不了配置
![image](https://github.com/nacos-group/nacos-sdk-rust/assets/13491101/8e1e5ef3-bcff-4e12-84c9-1a664a732be8)

**Comment by onewe** [comment]
建议使用 `nacos` 在同样的场景下测试一下, 我这边没有 `rnacos` 测试环境, 不能验证问题

**Comment by CherishCai** [comment]
可以看下日志，是否链上 server 了？是否 rnacos 未支持 gRPC ？

**Comment by zhiweishq** [comment]
> 建议使用 `nacos` 在同样的场景下测试一下, 我这边没有 `rnacos` 测试环境, 不能验证问题

有没有nacos的小型版本，对于个人或者是小配置的机器，nacos还是挺吃力的

**Comment by zhiweishq** [comment]
> 可以看下日志，是否链上 server 了？是否 rnacos 未支持 gRPC ？

应该是连接上了，如果是获取不是那个不存在的字段或者组都没有报这个错，只有获取正确的字段才会报这个错

**Comment by CherishCai** [comment]
@zhiweishq 估计得你自己看下了，也有可能是哪些 rnacos 和官方 nacos-server 有不兼容的地方。

另外不建议使用 namespace 为 "" 的，很可能有坑。

**Comment by CherishCai** [comment]
错误有行号，代码可以看看以及 debug 应该能发现问题 @zhiweishq

**Comment by CherishCai** [comment]
@zhiweishq 可以看下上面的关联 issue， rnacos 作者会在新版本达成兼容

**Comment by CherishCai** [comment]
Close with https://github.com/heqingpan/rnacos/issues/36
