### ISSUE TITLE
Feature Requset : 可否支持一个 listConfig 的 api

### ISSUE THREAD

**Issue by ZhicongZheng** [nacos-group/nacos-sdk-rust#216]
我想使用这个 sdk 将生产环境或者测试环境中的 nacos 配置同步到本机的 nacos 中，但是现在  ConfigService 只有根据 data-id 获取配置，我想把所有的 data-id 都同步

**Comment by CherishCai** [comment]
你可以使用管控台上的 导出，再导入到目标环境。sdk 不具备这类管控需求

**Comment by ZhicongZheng** [comment]
ok, 感谢回复
