### ISSUE TITLE
Can we reduce the frequency of log outputs, or make them conditional?

### ISSUE THREAD

**Issue by hshe** [nacos-group/nacos-sdk-rust#217]
<img width="813" alt="image" src="https://github.com/nacos-group/nacos-sdk-rust/assets/8075773/a79c330c-c1a6-469e-b8b6-d012c40fead3">

**Comment by onewe** [comment]
Ok, I will resolve this in the 0.4.x version. Thank your report.

**Comment by CherishCai** [comment]
How do you think we can modify it? Or some more detailed discussions and submit a PR

**Comment by CherishCai** [comment]
How about 0.3.5 ? We change some INFO to DEBUG.

**Comment by hshe** [comment]
> How about 0.3.5 ? We change some INFO to DEBUG.

agree.

**Comment by CherishCai** [comment]
close with 0.3.5
