### ISSUE TITLE
密码包含@符号，会报用户错误

### ISSUE THREAD

**Issue by fumenglin** [nacos-group/nacos-sdk-rust#220]
let client_props = ClientProps::new()
        .server_addr(client.addr.clone())
        .namespace(client.namespace.clone())
        .app_name(APP_NAME)
        .auth_username(client.username.clone())
        .auth_password(pw); 此处如果pw是通过传值的方式，如原来为123@123，rust会转为123%40123。最后会报错 用户错误；

我的处理方式 let pw = client.password.replace("%40", "@"); 进行一次替换；

不知道这个如果不替换，有什么办法可以解决？

**Comment by CherishCai** [comment]
这是用了哪个版本？0.3.5 还会这样吗？

**Comment by CherishCai** [comment]
转义是应该的吧？可以 debug 看看 HttpLoginAuthPlugin 的实现

**Comment by fumenglin** [comment]
就是0.35的版本

**Comment by CherishCai** [comment]
我认为密码就是 `123@123` ，转义成 `123%40123` 是 urlencode 的过程，服务端反转义得到 `123@123`

**Comment by fumenglin** [comment]
对的，nacos的参数我是通过URL的格式传入的，解析后我利用urlencoding::decode再次decode后就可以了；谢谢
