### ISSUE TITLE
ConfigService is not Send + Sync

### ISSUE THREAD

**Issue by thynson** [nacos-group/nacos-sdk-rust#227]
https://github.com/nacos-group/nacos-sdk-rust/blob/207421aad7bbf0f0f0e7945b9b94bd91977028b5/src/api/config.rs#L22C11-L22C24

Better changed to 

```rust
pub trait ConfigService: Send + Sync {
//...
}
```

So that `ConfigService` can be async friendlier.

**Comment by CherishCai** [comment]
Could you please make a PR?  for  `ConfigService` and `NameingService `
