### ISSUE TITLE
什么时候把依赖中的tonic升级到0.12版本?

### ISSUE THREAD

**Issue by gy0801151351** [nacos-group/nacos-sdk-rust#236]
目前发现0.4版本的nacos-sdk-rust依旧使用的是tonic 0.10版本. 这个版本的tonic使用的还是axum 0.6和hyper 0.14. 对于新项目来说, 这个版本的依赖有些旧了. tonic 0.12版本的api相对于tonic 0.10版本, 没有多少变化, 希望尽快升级一下依赖.

**Comment by CherishCai** [comment]
最新的 main 代码已经是了，你试试？

**Comment by gy0801151351** [comment]
已了解. 感谢告知
