### ISSUE TITLE
pub (crate)  struct NacosConfigService...

### ISSUE THREAD

**Issue by cfnet** [nacos-group/nacos-sdk-rust#238]
![image](https://github.com/user-attachments/assets/3c324c85-a65d-4d8d-bfcc-ae54b3b5bd3e)

![image](https://github.com/user-attachments/assets/73850aae-0038-4547-9895-02c1369b6655)
![image](https://github.com/user-attachments/assets/46babb72-58d2-421e-aafe-f6b03fd43cad)

Rust环境：
rustc 1.80.0 (051478957 2024-07-21)

**Comment by CherishCai** [comment]
接口公开的，实现确实在刚开始隐藏起来了。

**Comment by CherishCai** [comment]
我本地也是 rust 1.80 ，没有这个问题。使用 LazyLock 也可以跑，pls see https://github.com/nacos-group/nacos-sdk-rust/pull/239

**Comment by cfnet** [comment]
感谢，已经找到问题所有，忘记来看看啊。该问题关闭。
