### ISSUE TITLE
feature: 什么时候支持accessKey/secretKey

### ISSUE THREAD

**Issue by mattjin** [nacos-group/nacos-sdk-rust#247]

**Comment by CherishCai** [comment]
最新版 0.4.2 支持了的，你看下 CHANGELOG。

缺少 demo 同时把 README.md 的说明修改一下

**Comment by luoxiner** [comment]
demo 和文档已经通过新的pr提交了，可以关注一下 [pr](https://github.com/nacos-group/nacos-sdk-rust/pull/248)
