### ISSUE TITLE
nacos-macro的版本号维护存在问题

### ISSUE THREAD

**Issue by wfeii1980** [nacos-group/nacos-sdk-rust#251]
一些之前引用了`nacos-sdk=0.3`版本的项目，会因为`nacos-macro`升级到`0.1.1`而出现兼容性错误编译失败。

https://doc.rust-lang.org/cargo/reference/resolver.html?highlight=version#resolver-versions

**Comment by CherishCai** [comment]
理解了，存在可能的不兼容依赖的话，将其升级中间版本号，比如是 0.2.0 就没事对吧

**Comment by CherishCai** [comment]
确实是没有想到的点，感谢。在一下提交引入的问题
> bump: upgrade nacos-sdk=0.4.2, with nacos-macro=0.1.1 (https://github.com/nacos-group/nacos-sdk-rust/pull/246)

**Comment by CherishCai** [comment]
看来可行的方案是 yank 掉 nacos-macro=0.1.1，重新打一个 nacos-macro=0.2.0 以及 nacos-sdk=0.4.3

**Comment by wfeii1980** [comment]
> 理解了，存在可能的不兼容依赖的话，将其升级中间版本号，比如是 0.2.0 就没事对吧

是的

**Comment by CherishCai** [comment]
> 看来可行的方案是 yank 掉 nacos-macro=0.1.1，重新打一个 nacos-macro=0.2.0 以及 nacos-sdk=0.4.3

@wfeii1980 按照这样处理了，看看是否能行
