### ISSUE TITLE
Feature: 自定义传参 + ENV 环境变量读取

### ISSUE THREAD

**Issue by CherishCai** [nacos-group/nacos-sdk-rust#47]
- 创建参数，自定义传参 + ENV 环境变量读取，后者优先级高；
- ENV 统一前缀，例如 NACOS_CLIENT_CONFIG_* 于配置管理， NACOS_CLIENT_NAMING_* 于服务注册

**Comment by CherishCai** [comment]
https://crates.io/crates/dotenvy 有个 dotenvy 包，协助测试开发

**Comment by mxsm** [comment]
@CherishCai  Could you provide a more specific description of the requirement, or perhaps give an example?

**Comment by CherishCai** [comment]
> @CherishCai Could you provide a more specific description of the requirement, or perhaps give an example?

emmm, 其实不够清晰 Rust 针对这部分如何设计更佳，没有足够地参考其它项目。
感觉上就是 ENV 前缀分清楚些，分开各部分的使用，通用的使用。

- 形如已有的 `pub const ENV_NACOS_CLIENT_COMMON_THREAD_CORES: &str = "NACOS_CLIENT_COMMON_THREAD_CORES";` 
- 建议 NACOS_CLIENT_CONFIG_* 于配置管理， NACOS_CLIENT_NAMING_* 于服务注册；

做到能让环境变量优先设置目前 ClientProps (server_addr, namespace, app_name, username, password) 属性等，

**Comment by CherishCai** [comment]
> @CherishCai Could you provide a more specific description of the requirement, or perhaps give an example?

emmm, 其实不够清晰 Rust 针对这部分如何设计更佳，没有足够地参考其它项目。
感觉上就是 ENV 前缀分清楚些，分开各部分的使用，通用的使用。

- 形如已有的 `pub const ENV_NACOS_CLIENT_COMMON_THREAD_CORES: &str = "NACOS_CLIENT_COMMON_THREAD_CORES";` 
- 建议 NACOS_CLIENT_CONFIG_* 于配置管理， NACOS_CLIENT_NAMING_* 于服务注册；

做到能让环境变量优先设置目前 ClientProps (server_addr, namespace, app_name, username, password) 属性等，

**Comment by mxsm** [comment]
> > @CherishCai Could you provide a more specific description of the requirement, or perhaps give an example?
> 
> emmm, 其实不够清晰 Rust 针对这部分如何设计更佳，没有足够地参考其它项目。 感觉上就是 ENV 前缀分清楚些，分开各部分的使用，通用的使用。
> 
> * 形如已有的 `pub const ENV_NACOS_CLIENT_COMMON_THREAD_CORES: &str = "NACOS_CLIENT_COMMON_THREAD_CORES";`
> 
> 做到能让环境变量优先设置 ClientProps (server_addr, namespace, app_name, username, password) 属性等，或者在获取时优先环境变量

了解！
