### ISSUE TITLE
ServiceInstance.cluster_name不生效

### ISSUE THREAD

**Issue by tianyucn** [nacos-group/nacos-sdk-rust#82]
例如：
// new service instance
        let service_instance = ServiceInstance {
            ip,
            port,
            cluster_name: Some("testClusterName".to_string()),
            service_name: Some("simpleService".to_string()),
            ..Default::default()
        };

// register instance
        let register_ret = naming_service.batch_register_instance(
            "simpleService".to_string(),
            Some(constants::DEFAULT_GROUP.to_string()),
            vec![service_instance],
        );

sleep(Duration::from_secs(3)).await;
        let instances_ret = naming_service.get_all_instances(
           "simpleService".to_string(),
            Some(constants::DEFAULT_GROUP.to_string()),
            vec!["DEFAULT".to_string()],
            false,
        );
        match instances_ret {
            Ok(instances) => tracing::info!("get_all_instances {:?}", instances),
            Err(err) => tracing::error!("naming get_all_instances error {:?}", err),
        }

这样是可以查出数据的，感觉register_instance默认就是注册到cluster_name="DEFAULT"

**Comment by CherishCai** [comment]
可以到管控台上，看看服务下的实例，集群字段也是可以看到的。
