### ISSUE TITLE
'clusters' is invalid when call naming_service.subscribe()，fn 'event' can't running at NamingEventListener

### ISSUE THREAD

**Issue by tianyucn** [nacos-group/nacos-sdk-rust#85]
在调用naming_service.subscribe()方法时，自定义clusters（例如：let clusters = vec!["default".to_string()];），trait NamingEventListener的event方法不生效。如果clusters = Vec::default(); NamingEventListener的event生效。

以examples/simple_app.rs为例子：

    // ----------  Naming  -------------
    let mut naming_service = NamingServiceBuilder::new(client_props).build()?;
    // let clusters = vec!["default".to_string()]; /// 不生效
    let clusters = Vec::default(); /// 生效

    let listener = std::sync::Arc::new(SimpleInstanceChangeListener);
    let _subscribe_ret = naming_service.subscribe(
        "test-service".to_string(),
        Some(constants::DEFAULT_GROUP.to_string()),
        clusters,
        listener,
    );

pub struct SimpleInstanceChangeListener;

impl NamingEventListener for SimpleInstanceChangeListener {
    fn event(&self, event: std::sync::Arc<NamingChangeEvent>) {
        tracing::info!("subscriber notify: {:?}", event);
    }
}

**Comment by CherishCai** [comment]
最近有用户使用起来了，遇到问题我们尽快修复。版本不那么快发布的话，麻烦指定下 commit Id 使用 💗

**Comment by CherishCai** [comment]
@tianyucn 或者你可以提 PR 吗

**Comment by onewe** [comment]
我本地跑了一下 在注册服务时不指定 cluster_name 默认是注册在 DEFAULT 集群下的, 那么订阅时 如果要指定 cluster name 也需要指定 为 DEFAULT

**Comment by onewe** [comment]
订阅时如果不指定 cluster name 默认是订阅集群是 DEFAULT

**Comment by tianyucn** [comment]
> 我本地跑了一下 在注册服务时不指定 cluster_name 默认是注册在 DEFAULT 集群下的, 那么订阅时 如果要指定 cluster name 也需要指定 为 DEFAULT

目前在注册的时候cluster_name=default（小写），订阅的时候cluster_name=default（小写），fn event无法触发

**Comment by tianyucn** [comment]
> @tianyucn 或者你可以提 PR 吗

有时间的话，我会提交PR

**Comment by onewe** [comment]
看看是不是用的 0.2.2 最新的版本 昨晚上 有个序列化的 bug 我修复了

**Comment by tianyucn** [comment]
确认版本为0.2.2，当前是基于昨天晚上修复的最新版本来跑的。
昨天bug修复后，event中instance的cluster_name、service_name不是None了。

**Comment by onewe** [comment]
能给个 example 代码我跑跑吗？？ 我跑着没得问题.

``` rust
let naming_service = NacosNamingService::new(props, Arc::new(NoopAuthPlugin::default()))?;
        let service_instance1 = ServiceInstance {
            ip: "127.0.0.1".to_string(),
            port: 9090,
            metadata: metadata.clone(),
            cluster_name: Some("default".to_string()),
            ..Default::default()
        };

        let service_instance2 = ServiceInstance {
            ip: "192.168.1.1".to_string(),
            port: 8888,
            metadata: metadata.clone(),
            cluster_name: Some("default".to_string()),
            ..Default::default()
        };

        let service_instance3 = ServiceInstance {
            ip: "172.0.2.1".to_string(),
            port: 6666,
            metadata: metadata.clone(),
            cluster_name: Some("default".to_string()),
            ..Default::default()
        };
        let instance_vec = vec![service_instance1, service_instance2, service_instance3];

        let ret = naming_service.batch_register_instance(
            "test-service".to_string(),
            Some(constants::DEFAULT_GROUP.to_string()),
            instance_vec,
        );
        info!("response. {:?}", ret);

        let listener = Arc::new(InstancesChangeEventListener);
        let ret = naming_service.subscribe(
            "test-service".to_string(),
            Some(constants::DEFAULT_GROUP.to_string()),
            vec!["default".to_string()],
            listener,
        );
```

**Comment by tianyucn** [comment]
use nacos_sdk::api::config::{
    ConfigChangeListener, ConfigResponse,
};
use nacos_sdk::api::constants;
use nacos_sdk::api::naming::{
    NamingChangeEvent, NamingEventListener, NamingService, NamingServiceBuilder, ServiceInstance,
};
use nacos_sdk::api::props::ClientProps;
use std::time::Duration;
use tokio::time::sleep;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    tracing_subscriber::fmt()
        .with_max_level(tracing::Level::DEBUG)
        .init();

    let client_props = ClientProps::new()
        .server_addr("0.0.0.0:8848")
        .namespace("")
        .app_name("test-service");

    // ----------  Naming  -------------
    let naming_service = NamingServiceBuilder::new(client_props).build()?;

    let listener = std::sync::Arc::new(SimpleInstanceChangeListener);
    let _subscribe_ret = naming_service.subscribe(
        "test-service".to_string(),
        Some(constants::DEFAULT_GROUP.to_string()),
        // vec!["default".to_string()], // 不触发event
        Vec::default(),// 触发event
        listener,
    );

    let service_instance = ServiceInstance {
        ip: "127.0.0.1".to_string(),
        port: 9090,
        cluster_name: Some("default".to_string()),
        ..Default::default()
    };
    let _register_instance_ret = naming_service.register_service(
        "test-service".to_string(),
        Some(constants::DEFAULT_GROUP.to_string()),
        service_instance,
    );
    sleep(Duration::from_millis(3000)).await;

    let instances_ret = naming_service.get_all_instances(
        "test-service".to_string(),
        Some(constants::DEFAULT_GROUP.to_string()),
        vec!["default".to_string()],
        false,
    );
    match instances_ret {
        Ok(instances) => tracing::info!("get_all_instances {:?}", instances),
        Err(err) => tracing::error!("naming get_all_instances error {:?}", err),
    }

    sleep(Duration::from_secs(300)).await;
    Ok(())
}

struct SimpleConfigChangeListener;

impl ConfigChangeListener for SimpleConfigChangeListener {
    fn notify(&self, config_resp: ConfigResponse) {
        tracing::info!("listen the config={}", config_resp);
    }
}

pub struct SimpleInstanceChangeListener;

impl NamingEventListener for SimpleInstanceChangeListener {
    fn event(&self, event: std::sync::Arc<NamingChangeEvent>) {
        tracing::info!("subscriber notify: {:?}", event);
    }
}

**Comment by tianyucn** [comment]
在我的example中，情况1可以触发listener中的event，打印了subscriber notify: xxx；情况2不能触发listener中的event，没有打印信息。

情况1：
let listener = std::sync::Arc::new(SimpleInstanceChangeListener);
let _subscribe_ret = naming_service.subscribe(
    "test-service".to_string(),
    Some(constants::DEFAULT_GROUP.to_string()),
    // vec!["default".to_string()], // 不触发event
    Vec::default(),// 触发event
    listener,
);

情况1：
let listener = std::sync::Arc::new(SimpleInstanceChangeListener);
let _subscribe_ret = naming_service.subscribe(
    "test-service".to_string(),
    Some(constants::DEFAULT_GROUP.to_string()),
    vec!["default".to_string()], // 不触发event
    //Vec::default(),// 触发event
    listener,
);

![image](https://user-images.githubusercontent.com/51066290/206659063-ffec8af6-966d-4bfe-8828-820589d69a0b.png)

**Comment by onewe** [comment]
加我 丁丁 sa5f24e
