### ISSUE TITLE
Grpc相关库，为什么不用tonic

### ISSUE THREAD

**Issue by swq123459** [nacos-group/nacos-sdk-rust#90]

**Comment by CherishCai** [comment]
Good question. 一开始也是用的 tonic 但是发觉不合适，如果能改的话，也希望用它

![image](https://user-images.githubusercontent.com/16837364/212584044-d39cd9a7-5ce4-4da1-97ad-11aaa694e5a2.png)

**Comment by shaodan** [comment]
@CherishCai 不是很明白有界流指的是什么？tonic现在也支持 [双向streaming](https://github.com/hyperium/tonic/blob/master/examples/src/streaming/client.rs#L51)

**Comment by CherishCai** [comment]
> @CherishCai 不是很明白有界流指的是什么？tonic现在也支持 [双向streaming](https://github.com/hyperium/tonic/blob/master/examples/src/streaming/client.rs#L51)

@shaodan 当时我也是 Rust 入门不久，初次使用 tonic ，开启双向 streaming 传入的 stream 是有界的是吗？

其实如果能做到 stream 不关闭，随时可以传入数据，那么在 Nacos 客户端与服务端中就能适用。

**Comment by CherishCai** [comment]
> @CherishCai 不是很明白有界流指的是什么？tonic现在也支持 [双向streaming](https://github.com/hyperium/tonic/blob/master/examples/src/streaming/client.rs#L51)

@shaodan 链接中样例我当时也看过，in_stream 的长度传入到 tonic client 中是固定了的，没法后期增加数据。

**Comment by shaodan** [comment]
> @shaodan 链接中样例我当时也看过，in_stream 的长度传入到 tonic client 中是固定了的，没法后期增加数据。

理解你的意思了，我想想有没有解决办法

**Comment by onewe** [comment]
@shaodan 0.3.x 版本将正式替换为 tonic
