### ISSUE TITLE
windows： error: failed to run custom build command for `grpcio-sys v0.10.3+1.44.0-patched`

### ISSUE THREAD

**Issue by livstyle** [nacos-group/nacos-sdk-rust#96]
windows编译时出现这个报错怎么解决 error: failed to run custom build command for `grpcio-sys v0.10.3+1.44.0-patched`

**Comment by CherishCai** [comment]
或者提供更多有效信息？现在 nacos-sdk 0.2.2 似乎用的 grpcio 是 0.12 版本也不太匹配。因为我用的是 Mac 可能比较难提供帮助

**Comment by livstyle** [comment]
error: failed to run custom build command for `grpcio-sys v0.12.0+1.46.5-patched`

Caused by:
  process didn't exit successfully: `D:\acode\lykjn\ilink-pay\target\debug\build\grpcio-sys-f3d64200f24459c8\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=grpc_wrap.cc
  cargo:rerun-if-changed=grpc
  cargo:rerun-if-env-changed=CARGO_CFG_TARGET_OS
  cargo:rerun-if-env-changed=GRPCIO_SYS_USE_PKG_CONFIG
  cargo:rerun-if-env-changed=CARGO_CFG_TARGET_OS
  cargo:rerun-if-env-changed=CARGO_CFG_TARGET_OS
  cargo:rerun-if-env-changed=CARGO_CFG_TARGET_OS
  cargo:rerun-if-env-changed=CXX
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-pc-windows-msvc")
  HOST = Some("x86_64-pc-windows-msvc")
  cargo:rerun-if-env-changed=CC_x86_64-pc-windows-msvc
  CC_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CC_x86_64_pc_windows_msvc
  CC_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-msvc
  CFLAGS_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_msvc
  CFLAGS_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  DEBUG = Some("true")
  cargo:rustc-link-search=native=D:\acode\lykjn\ilink-pay\target\debug\build\libz-sys-1e9d7653aeb202a1\out/build   
  cargo:rustc-link-search=native=D:\acode\lykjn\ilink-pay\target\debug\build\libz-sys-1e9d7653aeb202a1\out/lib     
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = Some("D:\\acode\\lykjn\\ilink-pay\\target\\debug\\build\\libz-sys-1e9d7653aeb202a1\\out/build")
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "D:\\ProgramFiles\\rust\\cargo_home\\registry\\src\\mirrors.ustc.edu.cn-12df342d903acd47\\grpcio-sys-0.12.0+1.46.5-patched\\grpc" "-G" "Visual Studio 16 2019" "-Thost=x64" "-Ax64" "-DgRPC_INSTALL=false" "-DgRPC_BUILD_CSHARP_EXT=false" "-DgRPC_BUILD_CODEGEN=false" "-DgRPC_BENCHMARK_PROVIDER=none" "-DgRPC_ZLIB_PROVIDER=package" "-DCMAKE_INSTALL_PREFIX=D:\\acode\\lykjn\\ilink-pay\\target\\debug\\build\\grpcio-sys-45f61d13ad193f6e\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_DEBUG= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Debug"

  --- stderr
  CMake Error: Could not create named generator Visual Studio 16 2019

  Generators
  * Unix Makefiles               = Generates standard UNIX makefiles.
    Ninja                        = Generates build.ninja files.
    Ninja Multi-Config           = Generates build-<Config>.ninja files.
    CodeBlocks - Ninja           = Generates CodeBlocks project files.
    CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
    CodeLite - Ninja             = Generates CodeLite project files.
    CodeLite - Unix Makefiles    = Generates CodeLite project files.
    Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
    Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
    Kate - Ninja                 = Generates Kate project files.
    Kate - Unix Makefiles        = Generates Kate project files.
    Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
    Sublime Text 2 - Unix Makefiles
                                 = Generates Sublime Text 2 project files.

  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 1

  build script failed, must exit now', D:\ProgramFiles\rust\cargo_home\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\cmake-0.1.49\src\lib.rs:1104:5
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\std\src\panicking.rs:575
     1: core::panicking::panic_fmt
               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library\core\src\panicking.rs:65
     2: cmake::fail
               at D:\ProgramFiles\rust\cargo_home\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\cmake-0.1.49\src\lib.rs:1104
     3: cmake::run
               at D:\ProgramFiles\rust\cargo_home\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\cmake-0.1.49\src\lib.rs:1082
     4: cmake::Config::build
               at D:\ProgramFiles\rust\cargo_home\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\cmake-0.1.49\src\lib.rs:819
     5: build_script_build::build_grpc
               at .\build.rs:249
     6: build_script_build::main
               at .\build.rs:520
     7: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6\library\core\src\ops\function.rs:251
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...

**Comment by CherishCai** [comment]
@livstyle 先降低 Rust 版本看看？你可以看下最近另一个 issue 1.66.1 开始和 grpcio 配合有些问题，我本地降低到 1.65.0 可以用。
`rustup default 1.65.0`

**Comment by livstyle** [comment]
![image](https://user-images.githubusercontent.com/77309755/221500805-fef08f65-543e-4dc2-b6f9-c9a2b6c50b73.png)
windows上跑起来grpcio-sys依赖crate需要的其他条件太多了，他这个库看起来也还不能用在生产上

**Comment by CherishCai** [comment]
这个库还是好几个大项目在用的，`tikv/grpc-rs` wrap 了 gRPC 官方的 C++ 库，确实是依赖和使用很重。
只是目前 nacos 的交互方式上，由于 tonic 当时在使用上不太合适，就选了 `tikv/grpc-rs`，未来 tonic 合适的话可以替换过去
